/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.nuvalence.barcode.scanner;

import com.google.zxing.*;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.pdf417.PDF417Reader;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {
    public static String parsePdf417Barcode(String filepath) throws IOException, ChecksumException, NotFoundException, FormatException {
        BufferedImage bf = ImageIO.read(new ByteArrayInputStream(Files.readAllBytes(Paths.get(filepath))));
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(bf)));
        return new PDF417Reader().decode(bitmap).getText();
    }

    public static void main(String[] args) {
        try {
            System.out.println(parsePdf417Barcode(args[0]));
        } catch (IOException | ChecksumException | NotFoundException | FormatException e) {
            System.err.println("Failed to parse barcode");
            e.printStackTrace();
            System.exit(1);
        }
    }
}
